[package]
name = "freetype-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
freetype = "0.7.2"

[dev-dependencies]
image = "0.25.1"
